name: play_games
description: A simple wrapper on top of Google Play Games Services (GPGS), including auth, achievement, and more.
version: 1.0.0
homepage: https://github.com/luanpotter/play_games

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.games.play.playgames
        pluginClass: PlayGamesPlugin
      ios:
        pluginClass: PlayGamesPlugin
